name: ${name}
version: ${version}
main: net.ttk1.HideMe
depend: [ProtocolLib]
author: ttk1
website: https://github.com/ttk1/HideMe

commands:
  hideme:
    description: hideme command.
    usage: /hideme <subcommand>
    aliases: hm

permissions:
  hideme.version:
    default: op
  hideme.list:
    default: op
  hideme.help:
    default: op
  hideme.status:
    default: op
  hideme.status.player:
    default: op
  hideme.hide:
    default: op
  hideme.hide.player:
    default: op
  hideme.show:
    default: op
  hideme.show.player:
    default: op
  hideme.bypass:
    default: op
